<?php
/**
 * $Id$
 * Copyright (c) 2008-2009 maetl (http://maetl.net)
 * Free Software under the conditions of LICENSE.
 */

/**
 * @package ransack
 * @subpackage analysis
 */

/**
 * Parses result of test run generated by Simpletest TextReporter.
 *
 * @package ransack
 * @subpackage analysis
 */
class SimpleTestReport {

	function analyze($command) {
		$this->report = shell_exec($command);
	}
	
	function getReport() {
		preg_match("/(Passes:\s)([0-9]+),/", $this->report, $passes);
		preg_match("/(Failures:\s)([0-9]+),/", $this->report, $fails);
		preg_match("/(Exceptions:\s)([0-9]+)/", $this->report, $errors);
		$test = new stdClass;
		$test->passes = $passes[2];
		$test->failures = $fails[2];
		$test->exceptions = $errors[2];
		$test->result = ((int)$test->failures > 0) ? false : true;
		$test->output = $this->report;
		return $test;
	}
	
}

?>