#!/usr/bin/env php
<?php
/**
 * Ransack task runner
 */
require_once 'web/config.php';
require_once 'lib/floe/tools/ShellScript.class.php';

ConsoleText::banner(dirname(__FILE__).'/BANNER');
ShellScript::start();

?>